namespace AIMSService.Model
{
    public class ClientTOMALDetailDto
    {
        public Guid Id { get; set; }
        public Guid ClientId { get; set; }

        public string? selected { get; set; }
        public int? mfsVerbalRawScore { get; set; }
        public int? mfsVerbalScaleScore { get; set; }
        public int? mfsVerbalPercentageRank { get; set; }
        public int? fmNonVerbalRawScore { get; set; }
        public int? fmNonVerbalScaleScore { get; set; }
        public int? fmNonVerbalPercentageRank { get; set; }
        public int? wsrVerbalRawScore { get; set; }
        public int? wsrVerbalScaleScore { get; set; }
        public int? wsrVerbalPercentageRank { get; set; }
        public int? avmNonVerbalRawScore { get; set; }
        public int? avmNonVerbalScaleScore { get; set; }
        public int? avmNonVerbalPercentageRank { get; set; }
        public int? orVerbalRawScore { get; set; }
        public int? orVerbalScaleScore { get; set; }
        public int? orVerbalPercentageRank { get; set; }
        public int? vsmNonVerbalRawScore { get; set; }
        public int? vsmNonVerbalScaleScore { get; set; }
        public int? vsmNonVerbalPercentageRank { get; set; }
        public int? prVerbalRawScore { get; set; }
        public int? prVerbalScaleScore { get; set; }
        public int? prVerbalPercentageRank { get; set; }
        public int? mflNonVerbalRawScore { get; set; }
        public int? mflNonVerbalScaleScore { get; set; }
        public int? mflNonVerbalPercentageRank { get; set; }
        public int? ofVerbalRawScore { get; set; }
        public int? ofVerbalScaleScore { get; set; }
        public int? ofVerbalPercentageRank { get; set; }
        public int? vsrNonVerbalRawScore { get; set; }
        public int? vsrNonVerbalScaleScore { get; set; }
        public int? vsrNonVerbalPercentageRank { get; set; }
        public int? lfVerbalRawScore { get; set; }
        public int? lfVerbalScaleScore { get; set; }
        public int? lfVerbalPercentageRank { get; set; }
        public int? mlNonVerbalRawScore { get; set; }
        public int? mlNonVerbalScaleScore { get; set; }
        public int? mlNonVerbalPercentageRank { get; set; }
        public int? dbVerbalRawScore { get; set; }
        public int? dbVerbalScaleScore { get; set; }
        public int? dbVerbalPercentageRank { get; set; }
        public int? lbVerbalRawScore { get; set; }
        public int? lbVerbalScaleScore { get; set; }
        public int? lbVerbalPercentageRank { get; set; }
        public int? mfsdVerbalRawScore { get; set; }
        public int? mfsdVerbalScaleScore { get; set; }
        public int? mfsdVerbalPercentageRank { get; set; }
        public int? wsrdVerbalRawScore { get; set; }
        public int? wsrdVerbalScaleScore { get; set; }
        public int? wsrdVerbalPercentageRank { get; set; }
        public int? mfsVmi { get; set; }
        public int? mfsCmi { get; set; }
        public int? mfsAri { get; set; }
        public int? fmNmi { get; set; }
        public int? fmCmi { get; set; }
        public int? fmFri { get; set; }
        public int? wsrVmi { get; set; }
        public int? wsrCmi { get; set; }
        public int? wsrLi { get; set; }
        public int? avmNmi { get; set; }
        public int? avmCmi { get; set; }
        public int? avmFri { get; set; }
        public int? orVmi { get; set; }
        public int? orCmi { get; set; }
        public int? orLi { get; set; }
        public int? vsmNmi { get; set; }
        public int? vsmCmi { get; set; }
        public int? vsmSri { get; set; }
        public int? prVmi { get; set; }
        public int? prCmi { get; set; }
        public int? prAri { get; set; }
        public int? prLi { get; set; }
        public int? mflNmi { get; set; }
        public int? mflCmi { get; set; }
        public int? mflFri { get; set; }
        public int? dfAci { get; set; }
        public int? dfSri { get; set; }
        public int? vsrLi { get; set; }
        public int? lfAci { get; set; }
        public int? lfSri { get; set; }
        public int? miAci { get; set; }
        public int? miSri { get; set; }
        public int? dbAci { get; set; }
        public int? lbAci { get; set; }
        public int? mfsdVdri { get; set; }
        public int? wsrdVdri { get; set; }
        public int? smVmi { get; set; }
        public int? smNmi { get; set; }
        public int? smCmi { get; set; }
        public int? smVdri { get; set; }
        public int? smAci { get; set; }
        public int? smSri { get; set; }
        public int? smFri { get; set; }
        public int? smAri { get; set; }
        public int? smli { get; set; }
        public int? indVmi { get; set; }
        public int? indNmi { get; set; }
        public int? indCmi { get; set; }
        public int? indVdri { get; set; }
        public int? indAci { get; set; }
        public int? indSri { get; set; }
        public int? indFri { get; set; }
        public int? indAri { get; set; }
        public int? indli { get; set; }
        public string? perVmi { get; set; }
        public string? perNmi { get; set; }
        public string? perCmi { get; set; }
        public string? perVdri { get; set; }
        public string? perAci { get; set; }
        public string? perSri { get; set; }
        public string? perFri { get; set; }
        public string? perAri { get; set; }
        public string? perli { get; set; }

    }
}
