CREATE TABLE mytable(
   Grade_equivalent                            NUMERIC(4,1) NOT NULL PRIMARY KEY 
  ,Sight_Word_Efficiency_raw_score_FROM        INTEGER 
  ,Sight_Word_Efficiency_raw_score_TO          INTEGER 
  ,Phonemic_Decoding_Efficiency_raw_score_FROM INTEGER 
  ,Phonemic_Decoding_Efficiency_raw_score_TO   INTEGER 
);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (1,0,18,0,5);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (1,18,25,5,8);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (1.2,26,32,9,11);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (1.5,33,37,12,15);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (1.8,38,41,16,17);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (2,42,44,18,19);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (2.2,45,48,20,22);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (2.5,49,54,23,25);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (2.8,55,57,26,27);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (3,58,60,28,29);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (3.2,61,63,30,31);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (3.5,64,66,32,33);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (3.8,67,67,34,35);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (4,68,68,36,36);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (4.2,NULL,NULL,37,37);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (4.5,69,69,38,38);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (4.8,70,70,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (5,71,71,39,39);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (5.2,72,72,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (5.5,73,73,40,40);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (5.8,74,74,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (6,NULL,NULL,41,41);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (6.2,75,75,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (6.5,76,76,42,42);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (6.8,77,77,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (7,NULL,NULL,43,43);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (7.2,78,78,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (7.5,79,79,44,44);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (8,80,80,45,45);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (8.5,81,81,46,46);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (8.8,82,82,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (9.2,83,83,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (9.5,84,84,47,47);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (10,85,85,48,48);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (10.5,86,86,49,49);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (10.8,87,87,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (11,88,88,50,50);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (11.2,89,89,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (11.5,90,90,51,51);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (12,91,91,NULL,NULL);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (12.5,92,92,52,52);
INSERT INTO mytable(Grade_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES (12.8,92,0,52,0);
