CREATE TABLE mytable(
   Age_equivalent                              VARCHAR(4) NOT NULL PRIMARY KEY
  ,Sight_Word_Efficiency_raw_score_FROM        INTEGER 
  ,Sight_Word_Efficiency_raw_score_TO          INTEGER 
  ,Phonemic_Decoding_Efficiency_raw_score_FROM INTEGER 
  ,Phonemic_Decoding_Efficiency_raw_score_TO   INTEGER 
);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('6-0',0,14,0,5);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('6-0',14,19,5,7);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('6-3',20,25,8,10);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('6-6',26,28,11,12);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('6-9',29,33,13,14);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('7-0',34,37,15,16);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('7-3',38,40,17,18);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('7-6',41,47,19,21);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('7-9',48,51,22,24);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('8-0',52,54,25,26);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('8-3',55,57,27,28);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('8-6',58,60,29,30);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('8-9',61,64,31,31);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('9-0',65,66,32,32);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('9-3',67,67,33,33);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('9-6',68,68,34,34);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('9-9',69,69,35,35);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('10-0',NULL,NULL,36,36);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('10-3',70,70,37,37);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('10-6',71,71,38,38);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('10-9',72,72,39,39);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('11-0',73,73,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('11-3',74,74,40,40);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('11-6',75,75,41,41);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('11-9',76,76,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('12-0',NULL,NULL,42,42);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('12-3',77,77,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('12-6',78,78,43,43);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('12-9',NULL,NULL,44,44);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('13-0',79,79,45,45);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('13-6',80,80,46,46);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('13-9',81,81,47,47);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('14-0',82,82,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('14-6',83,83,48,48);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('15-0',84,84,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('15-6',85,85,49,49);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('15-9',86,86,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('16-3',87,87,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('16-6',88,88,50,50);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('17-0',89,89,NULL,NULL);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('17-6',90,90,51,52);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('17-9',NULL,NULL,53,54);
INSERT INTO mytable(Age_equivalent,Sight_Word_Efficiency_raw_score_FROM,Sight_Word_Efficiency_raw_score_TO,Phonemic_Decoding_Efficiency_raw_score_FROM,Phonemic_Decoding_Efficiency_raw_score_TO) VALUES ('17',90,0,54,0);
